version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: server
    command: /usr/src/app/node_modules/.bin/nodemon ./bin/www
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./backend/.env_docker
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - app-network
  client:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: client
    command: /usr/src/app/node_modules/.bin/nodemon App
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
